name: Python tests

on:
  push:
    branches:
      - main
      - docs
      - feat/**
  pull_request:
    branches:
      - main
      - docs

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Install package in editable mode
        run: pip install -e .

      - name: Run tests
        run: pytest -q
